export type CatalogItem = {
  category: string;
  trade: string;
  name: string;
  description: string;
  unit: string;
  unitCost: number;
  laborHoursPerUnit: number;
  laborRate: number;
  wasteFactor: number;
  spruceSku: string;
  /** Approximate quantity per 1000 sq ft of living area */
  qtyPerKsf: number;
};

/** Baseline residential material catalog with Spruce-style SKUs */
export const MATERIAL_CATALOG: CatalogItem[] = [
  {
    category: "Lumber",
    trade: "Framing",
    name: '2x4 SPF Stud 8\'',
    description: "Standard wall studs",
    unit: "ea",
    unitCost: 4.85,
    laborHoursPerUnit: 0.08,
    laborRate: 65,
    wasteFactor: 0.1,
    spruceSku: "LUM-2X4-8",
    qtyPerKsf: 180,
  },
  {
    category: "Lumber",
    trade: "Framing",
    name: '2x6 SPF Stud 9\'',
    description: "Exterior wall studs",
    unit: "ea",
    unitCost: 8.4,
    laborHoursPerUnit: 0.1,
    laborRate: 65,
    wasteFactor: 0.1,
    spruceSku: "LUM-2X6-9",
    qtyPerKsf: 95,
  },
  {
    category: "Lumber",
    trade: "Framing",
    name: '2x10 DF #2 Joist 12\'',
    description: "Floor joists",
    unit: "ea",
    unitCost: 22.5,
    laborHoursPerUnit: 0.15,
    laborRate: 65,
    wasteFactor: 0.08,
    spruceSku: "LUM-2X10-12",
    qtyPerKsf: 42,
  },
  {
    category: "Sheathing",
    trade: "Framing",
    name: '7/16" OSB Sheathing 4x8',
    description: "Wall and roof sheathing",
    unit: "sheet",
    unitCost: 18.75,
    laborHoursPerUnit: 0.25,
    laborRate: 65,
    wasteFactor: 0.12,
    spruceSku: "SHT-OSB-716",
    qtyPerKsf: 55,
  },
  {
    category: "Sheathing",
    trade: "Framing",
    name: '3/4" T&G Subfloor 4x8',
    description: "Floor sheathing",
    unit: "sheet",
    unitCost: 42.0,
    laborHoursPerUnit: 0.3,
    laborRate: 65,
    wasteFactor: 0.1,
    spruceSku: "SHT-TG-34",
    qtyPerKsf: 32,
  },
  {
    category: "Roofing",
    trade: "Roofing",
    name: "Architectural Shingles",
    description: "30-year laminated shingles",
    unit: "sq",
    unitCost: 125,
    laborHoursPerUnit: 2.5,
    laborRate: 55,
    wasteFactor: 0.15,
    spruceSku: "ROF-ARCH-30",
    qtyPerKsf: 12,
  },
  {
    category: "Roofing",
    trade: "Roofing",
    name: "Synthetic Underlayment",
    description: "Roof underlayment roll",
    unit: "roll",
    unitCost: 89,
    laborHoursPerUnit: 0.5,
    laborRate: 55,
    wasteFactor: 0.1,
    spruceSku: "ROF-UL-SYN",
    qtyPerKsf: 1.2,
  },
  {
    category: "Insulation",
    trade: "Insulation",
    name: "R-21 Batts 2x6",
    description: "Exterior wall insulation",
    unit: "bag",
    unitCost: 58,
    laborHoursPerUnit: 0.8,
    laborRate: 48,
    wasteFactor: 0.08,
    spruceSku: "INS-R21-2X6",
    qtyPerKsf: 8,
  },
  {
    category: "Insulation",
    trade: "Insulation",
    name: "R-49 Blown Attic",
    description: "Attic insulation",
    unit: "bag",
    unitCost: 42,
    laborHoursPerUnit: 0.4,
    laborRate: 48,
    wasteFactor: 0.05,
    spruceSku: "INS-R49-BLN",
    qtyPerKsf: 14,
  },
  {
    category: "Drywall",
    trade: "Drywall",
    name: '1/2" Drywall 4x12',
    description: "Interior wallboard",
    unit: "sheet",
    unitCost: 16.5,
    laborHoursPerUnit: 0.45,
    laborRate: 52,
    wasteFactor: 0.12,
    spruceSku: "DRW-12-412",
    qtyPerKsf: 48,
  },
  {
    category: "Drywall",
    trade: "Drywall",
    name: "Joint Compound 5gal",
    description: "Finishing compound",
    unit: "bucket",
    unitCost: 18,
    laborHoursPerUnit: 0.2,
    laborRate: 52,
    wasteFactor: 0.1,
    spruceSku: "DRW-JC-5G",
    qtyPerKsf: 6,
  },
  {
    category: "Electrical",
    trade: "Electrical",
    name: "14/2 NM-B Wire 250ft",
    description: "Branch circuit cable",
    unit: "roll",
    unitCost: 78,
    laborHoursPerUnit: 1.2,
    laborRate: 75,
    wasteFactor: 0.1,
    spruceSku: "ELE-142-250",
    qtyPerKsf: 4,
  },
  {
    category: "Electrical",
    trade: "Electrical",
    name: "200A Load Center",
    description: "Main breaker panel",
    unit: "ea",
    unitCost: 185,
    laborHoursPerUnit: 4,
    laborRate: 75,
    wasteFactor: 0,
    spruceSku: "ELE-PNL-200",
    qtyPerKsf: 0.5,
  },
  {
    category: "Plumbing",
    trade: "Plumbing",
    name: '1/2" PEX Pipe 100ft',
    description: "Supply piping",
    unit: "coil",
    unitCost: 45,
    laborHoursPerUnit: 1.5,
    laborRate: 72,
    wasteFactor: 0.1,
    spruceSku: "PLB-PEX-12",
    qtyPerKsf: 3,
  },
  {
    category: "Plumbing",
    trade: "Plumbing",
    name: '3" PVC Drain Pipe 10\'',
    description: "DWV drain line",
    unit: "ea",
    unitCost: 14.5,
    laborHoursPerUnit: 0.6,
    laborRate: 72,
    wasteFactor: 0.08,
    spruceSku: "PLB-PVC-3",
    qtyPerKsf: 8,
  },
  {
    category: "HVAC",
    trade: "HVAC",
    name: "3-Ton Heat Pump",
    description: "Split system outdoor unit",
    unit: "ea",
    unitCost: 3200,
    laborHoursPerUnit: 12,
    laborRate: 85,
    wasteFactor: 0,
    spruceSku: "HVC-HP-3T",
    qtyPerKsf: 0.45,
  },
  {
    category: "HVAC",
    trade: "HVAC",
    name: 'Flexible Duct 8"',
    description: "Supply duct runs",
    unit: "ft",
    unitCost: 2.85,
    laborHoursPerUnit: 0.08,
    laborRate: 85,
    wasteFactor: 0.1,
    spruceSku: "HVC-FDX-8",
    qtyPerKsf: 220,
  },
  {
    category: "Windows",
    trade: "Windows & Doors",
    name: "Vinyl Double-Hung Window",
    description: "36x60 Low-E window",
    unit: "ea",
    unitCost: 285,
    laborHoursPerUnit: 2,
    laborRate: 60,
    wasteFactor: 0,
    spruceSku: "WIN-VDH-3660",
    qtyPerKsf: 6,
  },
  {
    category: "Doors",
    trade: "Windows & Doors",
    name: "Fiberglass Entry Door",
    description: "36in insulated entry",
    unit: "ea",
    unitCost: 620,
    laborHoursPerUnit: 3,
    laborRate: 60,
    wasteFactor: 0,
    spruceSku: "DOR-FG-36",
    qtyPerKsf: 1.2,
  },
  {
    category: "Doors",
    trade: "Windows & Doors",
    name: "Hollow-Core Interior Door",
    description: "30in prehung",
    unit: "ea",
    unitCost: 95,
    laborHoursPerUnit: 1.2,
    laborRate: 55,
    wasteFactor: 0,
    spruceSku: "DOR-HC-30",
    qtyPerKsf: 8,
  },
  {
    category: "Concrete",
    trade: "Foundation",
    name: "Ready-Mix Concrete",
    description: "3000 PSI slab/footing",
    unit: "cy",
    unitCost: 155,
    laborHoursPerUnit: 1.5,
    laborRate: 58,
    wasteFactor: 0.05,
    spruceSku: "CON-RM-3000",
    qtyPerKsf: 18,
  },
  {
    category: "Concrete",
    trade: "Foundation",
    name: "#4 Rebar 20ft",
    description: "Slab reinforcement",
    unit: "ea",
    unitCost: 12.5,
    laborHoursPerUnit: 0.15,
    laborRate: 58,
    wasteFactor: 0.08,
    spruceSku: "CON-RB-4-20",
    qtyPerKsf: 35,
  },
  {
    category: "Siding",
    trade: "Exterior",
    name: "Fiber Cement Lap Siding",
    description: "Hardie-style 8.25in",
    unit: "sq",
    unitCost: 210,
    laborHoursPerUnit: 3.5,
    laborRate: 58,
    wasteFactor: 0.12,
    spruceSku: "SID-FC-825",
    qtyPerKsf: 14,
  },
  {
    category: "Hardware",
    trade: "Framing",
    name: "Joist Hanger Assortment",
    description: "Galvanized hangers & nails",
    unit: "box",
    unitCost: 48,
    laborHoursPerUnit: 0.5,
    laborRate: 65,
    wasteFactor: 0.05,
    spruceSku: "HDW-JH-AST",
    qtyPerKsf: 3,
  },
];

export const TRADE_ORDER = [
  "Foundation",
  "Framing",
  "Roofing",
  "Windows & Doors",
  "Exterior",
  "Plumbing",
  "Electrical",
  "HVAC",
  "Insulation",
  "Drywall",
];
