import { test } from "node:test";
import assert from "node:assert/strict";
import { PDFParse } from "pdf-parse";
import { generatePurchaseOrderPdf } from "../src/lib/documents/purchaseOrderPdf";

// KNOWN_LIMITATIONS.md said the PO document was "a print-friendly HTML page
// (window.print() -> 'Save as PDF' in any browser)... no pdfkit/binary
// generation pipeline is wired up yet." This verifies the real pipeline
// against a real PDF parser (pdf-parse) reading the generated bytes back —
// not just checking the output is non-empty or starts with "%PDF-".

const BASE_PO = {
  poNumber: "PO-1001",
  status: "issued",
  organizationName: "Acme Buyer Co",
  supplierName: "Widget Supply Co",
  supplierAddress: "123 Main St, Springfield, IL, 62704, US",
  billingAddress: "456 Billing Ave",
  shippingAddress: "789 Ship Ln",
  paymentTerms: "Net 30",
  requestedDeliveryDate: new Date("2026-09-01"),
  createdAt: new Date("2026-08-19"),
  lineItems: [{ description: "200A Panel", sku: "SKU-1", quantity: 2, unitPrice: 150.5, total: 301 }],
  freight: 25,
  tax: 10,
  total: 336,
};

test("generatePurchaseOrderPdf produces a real, valid PDF binary", async () => {
  const pdf = await generatePurchaseOrderPdf(BASE_PO);
  assert.equal(pdf.subarray(0, 5).toString(), "%PDF-");
  assert.ok(pdf.length > 500); // not a truncated/empty stub
});

test("the generated PDF's text content, read back by a real PDF parser, contains every field", async () => {
  const pdf = await generatePurchaseOrderPdf(BASE_PO);
  const parser = new PDFParse({ data: pdf });
  const result = await parser.getText();

  assert.match(result.text, /PO-1001/);
  assert.match(result.text, /issued/);
  assert.match(result.text, /Acme Buyer Co/);
  assert.match(result.text, /Widget Supply Co/);
  assert.match(result.text, /123 Main St, Springfield, IL, 62704, US/);
  assert.match(result.text, /Net 30/);
  assert.match(result.text, /789 Ship Ln/);
  assert.match(result.text, /200A Panel/);
  assert.match(result.text, /SKU-1/);
  assert.match(result.text, /\$150\.50/);
  assert.match(result.text, /\$301\.00/);
  assert.match(result.text, /\$25\.00/); // freight
  assert.match(result.text, /\$10\.00/); // tax
  assert.match(result.text, /\$336\.00/); // total
});

test("null optional fields render as an em dash rather than the literal string 'null'", async () => {
  const pdf = await generatePurchaseOrderPdf({
    ...BASE_PO,
    supplierAddress: null,
    billingAddress: null,
    shippingAddress: null,
    paymentTerms: null,
    requestedDeliveryDate: null,
    freight: null,
    tax: null,
    total: null,
  });
  const parser = new PDFParse({ data: pdf });
  const result = await parser.getText();

  assert.doesNotMatch(result.text, /null/i);
  assert.match(result.text, /—/); // em dash placeholder used throughout
});

test("multiple line items all appear, each with its own correct total", async () => {
  const pdf = await generatePurchaseOrderPdf({
    ...BASE_PO,
    lineItems: [
      { description: "200A Panel", sku: "SKU-1", quantity: 2, unitPrice: 150.5, total: 301 },
      { description: "Conduit Fitting", sku: null, quantity: 50, unitPrice: 3.25, total: 162.5 },
    ],
  });
  const parser = new PDFParse({ data: pdf });
  const result = await parser.getText();

  assert.match(result.text, /200A Panel/);
  assert.match(result.text, /Conduit Fitting/);
  assert.match(result.text, /\$301\.00/);
  assert.match(result.text, /\$162\.50/);
});
