import type { ProposalCategory, ShopPackage } from "@buildiq/types";

/** Hardcoded shop packages aligned to proposal / pricing categories */
export const SHOP_PACKAGES: ShopPackage[] = [
  {
    id: "pkg-windows",
    slug: "windows-residential-takeoff",
    category: "Windows" as ProposalCategory,
    name: "Windows Takeoff Package",
    description: "Vinyl / fiberglass window package sized from plan takeoff quantities.",
    contents: [
      "Vinyl double-hung Low-E windows",
      "Picture / fixed units as specified",
      "Nailing fins & installation accessories",
      "Rough opening schedule from takeoff",
    ],
    unitPrice: 12800,
    leadDays: 21,
    spruceSku: "PKG-WIN-RES",
  },
  {
    id: "pkg-doors",
    slug: "doors-residential-takeoff",
    category: "Doors",
    name: "Doors Takeoff Package",
    description: "Entry, interior, and patio door package from door schedule takeoff.",
    contents: [
      "Fiberglass insulated entry door(s)",
      "Prehung interior doors",
      "Sliding / French patio unit as noted",
      "Door unit schedule from takeoff",
    ],
    unitPrice: 6400,
    leadDays: 14,
    spruceSku: "PKG-DOR-RES",
  },
  {
    id: "pkg-lumber",
    slug: "lumber-framing-takeoff",
    category: "Lumber",
    name: "Lumber Framing Package",
    description: "Stud, plate, joist, and beam lumber package for residential framing takeoff.",
    contents: [
      "2x4 / 2x6 SPF studs & plates",
      "Floor / ceiling joists",
      "Headers & beams (DF / LVL as scoped)",
      "Cut list aligned to framing takeoff",
    ],
    unitPrice: 18500,
    leadDays: 5,
    spruceSku: "PKG-LUM-FRM",
  },
  {
    id: "pkg-trusses",
    slug: "trusses-roof-takeoff",
    category: "Trusses",
    name: "Roof Truss Package",
    description: "Engineered roof truss package with layout from roof plan takeoff.",
    contents: [
      "Common / hip / valley trusses",
      "Gable end frames",
      "Bracing & hardware kit",
      "Stamped layout drawings",
    ],
    unitPrice: 9200,
    leadDays: 18,
    spruceSku: "PKG-TRS-ROF",
  },
  {
    id: "pkg-cabinetry",
    slug: "cabinetry-kitchen-bath",
    category: "Cabinetry",
    name: "Cabinetry Takeoff Package",
    description: "Kitchen and bath cabinet package from elevation / plan takeoff.",
    contents: [
      "Base & wall kitchen cabinets",
      "Vanity cabinets",
      "Toe kicks, fillers, panels",
      "Cabinet schedule from takeoff",
    ],
    unitPrice: 15400,
    leadDays: 28,
    spruceSku: "PKG-CAB-KB",
  },
  {
    id: "pkg-masonry",
    slug: "masonry-stone-veneer",
    category: "Masonry Stone",
    name: "Masonry Stone Package",
    description: "Stone veneer and masonry package for elevations from takeoff SF.",
    contents: [
      "Cultured / natural stone veneer",
      "Corners & trim pieces",
      "Mortar / thinset materials",
      "Elevation SF from takeoff",
    ],
    unitPrice: 7800,
    leadDays: 12,
    spruceSku: "PKG-MAS-STN",
  },
  {
    id: "pkg-hardware",
    slug: "door-hardware-residential",
    category: "Door Hardware",
    name: "Door Hardware Package",
    description: "Locks, hinges, and stops matched to the door schedule.",
    contents: [
      "Entry locksets",
      "Passage / privacy knobs",
      "Hinges & door stops",
      "Hardware schedule from takeoff",
    ],
    unitPrice: 2100,
    leadDays: 7,
    spruceSku: "PKG-HW-DOR",
  },
  {
    id: "pkg-millwork",
    slug: "millwork-trim-package",
    category: "Millwork",
    name: "Millwork & Trim Package",
    description: "Interior trim, casing, and base from finish schedule takeoff.",
    contents: [
      "Door / window casing",
      "Baseboard & shoe",
      "Chair rail / crown as scoped",
      "LF schedule from takeoff",
    ],
    unitPrice: 4500,
    leadDays: 10,
    spruceSku: "PKG-MLW-TRM",
  },
];

export function findShopPackage(packageId: string) {
  return SHOP_PACKAGES.find((p) => p.id === packageId || p.slug === packageId) ?? null;
}
