/** Default Supply Monkey cabinetry product lines — specs editable in DB. */

export const DEFAULT_CABINETRY_LINES = [
  {
    slug: "mesa",
    name: "Mesa",
    sortOrder: 1,
    description: "Frameless residential cabinetry with configurable laminate finish.",
    specs: {
      construction: "Frameless",
      box: "3/4-inch plywood boxes",
      stretchers: "3/4-inch recessed stretchers and nailers",
      toeKick: "3/4-inch toe kick",
      drawers: "3/4-inch drawer boxes",
      hardware: "Soft-close drawers and hinges",
      finish: "Configurable laminate finish and interior specifications",
    },
  },
  {
    slug: "summit",
    name: "Summit",
    sortOrder: 2,
    description: "Frameless cabinetry with upgraded finish and interior options.",
    specs: {
      construction: "Frameless",
      box: "3/4-inch plywood boxes",
      stretchers: "3/4-inch recessed stretchers and nailers",
      toeKick: "3/4-inch toe kick",
      drawers: "3/4-inch drawer boxes",
      hardware: "Soft-close drawers and hinges",
      finish: "Upgraded finish and interior options",
    },
  },
  {
    slug: "pinnacle",
    name: "Pinnacle",
    sortOrder: 3,
    description: "Premium frameless cabinetry with grain-matching and veneer options.",
    specs: {
      construction: "Frameless",
      box: "3/4-inch plywood boxes",
      stretchers: "3/4-inch recessed stretchers and nailers",
      toeKick: "3/4-inch toe kick",
      drawers: "3/4-inch drawer boxes",
      hardware: "Soft-close drawers and hinges",
      interiors: "Matching finished interiors where selected",
      grainMatching: true,
      bookMatchedVeneer: true,
      finish: "Premium finish options",
    },
  },
] as const;

export const CABINETRY_STAGES = [
  "NEW",
  "DOCUMENTS_REQUESTED",
  "DOCUMENTS_RECEIVED",
  "AI_PROCESSING",
  "ESTIMATING",
  "CLARIFICATION_REQUIRED",
  "INTERNAL_REVIEW",
  "PROPOSAL_READY",
  "PROPOSAL_SENT",
  "REVISION_REQUESTED",
  "ACCEPTED",
  "DEPOSIT_PENDING",
  "DEPOSIT_PAID",
  "LOST",
  "EXPIRED",
] as const;
